import heroImg from "$lib/enhanced_img/methodMinder/hero.png?enhanced";
import figma from "$lib/enhanced_img/methodMinder/figma.png?enhanced";
import arrayMethods from "$lib/enhanced_img/methodMinder/arrayMethods.png?enhanced";
import routes from "$lib/enhanced_img/methodMinder/routes.png?enhanced";
import spacedRep from "$lib/enhanced_img/methodMinder/spacedRep.png?enhanced";
import arrayResponsive from "$lib/enhanced_img/methodMinder/array_responsive.png?enhanced";

export let introData = {
  title: "MethodMinder - LLM Flashcards",
  para: [
    "This project combines Anki's spaced repetition algorithm with OpenAI's content generation to create a learning tool for JavaScript array methods.",
    "Users can review flashcards using the spaced repetition technique, which optimizes memory retention by scheduling reviews based on user performance.",
    "This is an MVP to test my flashcard idea. It uses localStorage and is all client-side, so I'd expose my OpenAI key and usage allowance if I deployed it.",
    "There's a link to my GitHub below so it can be cloned and your own OpenAI key entered (or switch LLM).",
    "I'm happy with the MVP and am now building it as a full-stack web app with Next.js and Supabase."
  ],
  techStack: [
    {
      title: "Stack:",
      description: "React &nbsp; | &nbsp; React Router &nbsp; | &nbsp; OpenAI API"
    },
    {
      title: "GitHub:",
      description: "<a href=\"https://github.com/CW-Logothetis/methodMinderMVP\" class=\"intro--para-col-2\" target=\"_blank\" rel=\"noreferrer\">MethodMinder repo</a>"
    }
  ]
};

export let heroImage = {
  src: heroImg,
  alt: "Screenshot of the app's home screen with flashcards for each array method."
};

export let processData = {
  "sectionHeader": "Process",
  "steps": [
    {
      "text": [
        "Wireframes for the pages in Figma.",
        "Concentrating on the flow through the flashcards.",
        "And thinking how to add multiple decks and a reference library"
      ],
      "colorClass": "bubble-4-blue",
      "image": figma,
      "alt": "Screenshot of the responsive homepage layout."
    },
    {
      "text": [
        "Used OpenAI to generate a deck of the 37 array methods (prototype and static).",
        "These have a short description and keys for the spaced repetition process."
      ],
      "colorClass": "bubble-4-blue",
      "image": arrayMethods,
      "alt": "Screenshot showing OpenAI-generated content."
    },
    {
      "text": [
        "Implemented dynamic routing using React Router to handle navigation between different flashcards and reference pages.",
        "Each array method has its own 'page' that displays the OpenAI-generated content and allows users to review and score their understanding."
      ],
      "colorClass": "bubble-4-blue",
      "image": routes,
      "alt": "Screenshot of a dynamically generated array method page."
    },
    {
      "text": [
        "Adapted Anki's spaced repetition algorithm to schedule flashcard reviews based on user performance.",
        "The algorithm optimizes memory retention by adjusting the review intervals for each flashcard, ensuring that users review material just before they are likely to forget it."
      ],
      "colorClass": "bubble-4-blue",
      "image": spacedRep,
      "alt": "Screenshot showing the spaced repetition algorithm in action."
    },
    {
      "text": [
        "A reference for all array methods (also generated by OpenAI) with CSS Grid and Flexbox.",
        "They make it naturally responsive and there's no need for any media queries.",
        "The colour scheme is based on the JavaScript logo."
      ],
      "colorClass": "bubble-4-blue",
      "image": arrayResponsive,
      "alt": "screenshot from app"
    },
  ]
};